Minor Fixes
bitsacm/sig_tracker pull request #9
Opened 2018-07-11 06:13 UTC by siddhantkhandelwal

Minor typo fixes, README update.

2018-07-11 06:20 UTC, apb7 requested changes

2018-07-11 06:20 UTC, apb7 commented on sig_tracker/about_sig/urls.py
> +    url(r'^', views.index, name='index'),
Did you try this out? Putting a caret here means the URL should start from this point. Therefore, the URL `/about_sig/` will not match any pattern.

2018-07-11 06:20 UTC, apb7 commented on sig_tracker/dev_sig/urls.py
> +    url(r'^', views.index, name='index'),
Ditto (here and below).

2018-07-11 06:20 UTC, apb7 commented on sig_tracker/sig_tracker/urls.py
> +    url(r'^admin/', admin.site.urls),
I don't think this URL would match any pattern since the URL to match is `http://127.0.0.1:8000/admin`. Please check _all_ changes locally!

2018-07-11 06:23 UTC, siddhantkhandelwal commented on sig_tracker/sig_tracker/urls.py
> +    url(r'^admin/', admin.site.urls),
Works fine on my system!

2018-07-11 06:24 UTC, siddhantkhandelwal commented on sig_tracker/dev_sig/urls.py
> +    url(r'^', views.index, name='index'),
Works fine on my system!

2018-07-11 06:24 UTC, siddhantkhandelwal commented on sig_tracker/about_sig/urls.py
> +    url(r'^', views.index, name='index'),
Works fine on my system!

2018-07-11 06:48 UTC, apb7 reviewed
Hi @siddhantkhandelwal, while you are at it, can you please fix other indentation problems in `about_sig/models.py`? Some functions there seem to be indented by 5 (/cc @sharifa2708?).
Please correct any other such errors if you come across them! That will be great :+1:

2018-07-11 06:48 UTC, apb7 commented on sig_tracker/about_sig/urls.py
> +    url(r'^', views.index, name='index'),
Wierd; It's working for me too. Never mind, thanks for checking. :)

2018-07-11 06:48 UTC, apb7 commented on sig_tracker/about_sig/urls.py
> +    url(r'^', views.index, name='index'),
Here and below as well.

2018-07-12 08:07 UTC, siddhantkhandelwal commented
Indentation Fixes have been implemented. Please Review.

2018-07-12 10:02 UTC, apb7 reviewed
Hi @siddhantkhandelwal, just a single comment!

2018-07-12 10:02 UTC, apb7 commented on sig_tracker/about_sig/templates/about_sig/detail.html
> +	{{sig.co_ordinator}}
Please follow an indentation of 2 spaces for HTML. It is generally more preferred. Change this here and below in this file.

2018-07-12 10:02 UTC, apb7 commented on sig_tracker/sig_tracker/settings.py
> +TIME_ZONE = 'Asia/Kolkata'
This is good!

2018-07-12 23:41 UTC, siddhantkhandelwal commented
Neat!

2018-07-13 05:25 UTC, apb7 approved these changes
LGTM! Thanks, @siddhantkhandelwal :100:

2018-07-13 05:25 UTC, merged